(function(){'use strict';var p=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=aa(this);
function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&p(c,a,{configurable:!0,writable:!0,value:b})}}function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function v(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function w(a){if(!(a instanceof Array)){a=v(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ca(a){return da(a,a)}function da(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}
function y(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var ea=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)y(d,e)&&(a[e]=d[e])}return a};u("Object.assign",function(a){return a||ea});function fa(){this.v=!1;this.l=null;this.u=void 0;this.g=1;this.C=this.h=0;this.o=null}
function ha(a){if(a.v)throw new TypeError("Generator is already running");a.v=!0}fa.prototype.A=function(a){this.u=a};function ia(a,b){a.o={T:b,W:!0};a.g=a.h||a.C}fa.prototype.return=function(a){this.o={return:a};this.g=this.C};function z(a,b,c){a.g=c;return{value:b}}function C(a){a.h=0;a.o=null}function ja(a){this.g=new fa;this.h=a}function ka(a,b){ha(a.g);var c=a.g.l;if(c)return la(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return E(a)}
function la(a,b,c,d){try{var e=b.call(a.g.l,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.v=!1,e;var h=e.value}catch(f){return a.g.l=null,ia(a.g,f),E(a)}a.g.l=null;d.call(a.g,h);return E(a)}function E(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.v=!1,{value:b.value,done:!1}}catch(c){a.g.u=void 0,ia(a.g,c)}a.g.v=!1;if(a.g.o){b=a.g.o;a.g.o=null;if(b.W)throw b.T;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ma(a){this.next=function(b){ha(a.g);a.g.l?b=la(a,a.g.l.next,b,a.g.A):(a.g.A(b),b=E(a));return b};this.throw=function(b){ha(a.g);a.g.l?b=la(a,a.g.l["throw"],b,a.g.A):(ia(a.g,b),b=E(a));return b};this.return=function(b){return ka(a,b)};this[Symbol.iterator]=function(){return this}}function na(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function F(a){return na(new ma(new ja(a)))}function oa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}u("globalThis",function(a){return a||t});
u("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.g=h;p(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return pa(ba(this))}});return a});function pa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
u("Promise",function(a){function b(f){this.h=0;this.l=void 0;this.g=[];this.A=!1;var g=this.o();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.h=function(f){if(this.g==null){this.g=[];var g=this;this.l(function(){g.u()})}this.g.push(f)};var e=t.setTimeout;c.prototype.l=function(f){e(f,0)};c.prototype.u=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.o(l)}}}this.g=null};c.prototype.o=function(f){this.l(function(){throw f;})};b.prototype.o=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.O),reject:f(this.u)}};b.prototype.O=function(f){if(f===this)this.u(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.R(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.N(f):this.v(f)}};
b.prototype.N=function(f){var g=void 0;try{g=f.then}catch(k){this.u(k);return}typeof g=="function"?this.S(g,f):this.v(f)};b.prototype.u=function(f){this.C(2,f)};b.prototype.v=function(f){this.C(1,f)};b.prototype.C=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.l=g;this.h===2&&this.P();this.Y()};b.prototype.P=function(){var f=this;e(function(){if(f.M()){var g=t.console;typeof g!=="undefined"&&g.error(f.l)}},1)};b.prototype.M=
function(){if(this.A)return!1;var f=t.CustomEvent,g=t.Event,k=t.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.l;return k(f)};b.prototype.Y=function(){if(this.g!=null){for(var f=0;f<this.g.length;++f)h.h(this.g[f]);this.g=null}};var h=new c;b.prototype.R=
function(f){var g=this.o();f.J(g.resolve,g.reject)};b.prototype.S=function(f,g){var k=this.o();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(n,r){return typeof n=="function"?function(x){try{l(n(x))}catch(A){m(A)}}:r}var l,m,q=new b(function(n,r){l=n;m=r});this.J(k(f,l),k(g,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.J=function(f,g){function k(){switch(l.h){case 1:f(l.l);break;case 2:g(l.l);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.g==null?h.h(k):this.g.push(k);this.A=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=v(f),m=l.next();!m.done;m=l.next())d(m.value).J(g,k)})};b.all=function(f){var g=v(f),k=g.next();return k.done?d([]):new b(function(l,m){function q(x){return function(A){n[x]=A;r--;r==0&&l(n)}}var n=[],r=0;do n.push(void 0),r++,d(k.value).J(q(n.length-1),m),k=g.next();while(!k.done)})};return b});
function qa(a,b,c){if(a==null)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}u("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"startsWith"),e=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<h&&c<e;)if(d[c++]!=b[f++])return!1;return f>=h}});
u("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"endsWith");c===void 0&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;e>0&&c>0;)if(d[--c]!=b[--e])return!1;return e<=0}});function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}
u("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}});
u("WeakMap",function(a){function b(k){this.g=(g+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!y(k,f)){var l=new c;p(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!y(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&y(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&y(k,
f)&&y(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&y(k,f)&&y(k[f],this.g)?delete k[f][this.g]:!1};return b});
u("Map",function(a){function b(){var g={};return g.B=g.next=g.head=g}function c(g,k){var l=g[1];return pa(function(){if(l){for(;l.head!=g[1];)l=l.B;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&y(g[0],l))for(g=0;g<m.length;g++){var q=m[g];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:g,entry:q}}return{id:l,
list:m,index:-1,entry:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=v(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(v([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(q){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],B:this[1].B,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].B.next=l.entry,this[1].B=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.B.next=g.entry.next,
g.entry.next.B=g.entry.B,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].B=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=
function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});
u("Set",function(a){function b(c){this.g=new Map;if(c){c=v(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(v([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),h=e.next();if(h.done||h.value[0]!=c||h.value[1]!=c)return!1;h=e.next();return h.done||h.value[0]==c||h.value[0].x!=4||
h.value[1]!=h.value[0]?!1:e.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=c===0?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(h){return c.call(d,h,h,e)})};return b});u("Array.prototype.entries",function(a){return a?a:function(){return ra(this,function(b,c){return[b,c]})}});u("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)y(b,d)&&c.push(b[d]);return c}});
u("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)y(b,d)&&c.push([d,b[d]]);return c}});
u("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});u("String.prototype.includes",function(a){return a?a:function(b,c){return qa(this,b,"includes").indexOf(b,c||0)!==-1}});
u("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}});u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});
u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var va=this||self;/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
var wa=window,xa={};wa.gapi=wa.gapi||xa;/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ya=globalThis.trustedTypes,za;function Aa(){var a=null;if(!ya)return a;try{var b=function(c){return c};a=ya.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a}function Ba(){za===void 0&&(za=Aa());return za};function Ca(a){this.g=a}Ca.prototype.toString=function(){return this.g+""};function Da(a){var b=Ba();a=b?b.createScriptURL(a):a;return new Ca(a)};function G(a){this.g=a}G.prototype.toString=function(){return this.g};function Ea(a){this.X=a}function H(a){return new Ea(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var Fa=[H("data"),H("http"),H("https"),H("mailto"),H("ftp"),new Ea(function(a){return/^[^:]*([/?#]|$)/.test(a)})];function I(a){var b=b===void 0?Fa:b;if(a instanceof G)return a;for(var c=0;c<b.length;++c){var d=b[c];if(d instanceof Ea&&d.X(a))return new G(a)}}var Ga=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function J(a,b){if(b instanceof G)if(b instanceof G)b=b.g;else throw Error("");else b=Ga.test(b)?b:void 0;b!==void 0&&(a.href=b)};function Ha(a){this.g=a}Ha.prototype.toString=function(){return this.g+""};function Ia(a){if(a instanceof Ha)return a;a=String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;");var b=Ba();a=b?b.createHTML(a):a;return new Ha(a)};var Ja=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/u\/(\d)\//;var Ka=new Set(Object.values({aa:"adg",ba:"aff",ca:"cam",da:"exp",ea:"gcl",fa:"inc"}).filter(function(a){return a!=="exp"}));function K(a){return a.toLowerCase().startsWith("v4")}
function L(a){var b=this;if(!K(a))throw Error("subid is not a v4 subid");a=a.split("~");this.Z=a.shift()||"";this.H=[];this.parameters={};this.L=[];a.forEach(function(c){if(c.toLowerCase().startsWith("exp-"))b.H.push.apply(b.H,w(c.substring(4).split("|").map(function(h){return h.startsWith("-")?h.substring(1):h})));else{for(var d=v(Ka),e=d.next();!e.done;e=d.next())if(e=e.value,c.toLowerCase().startsWith(e+"-")){b.parameters[e]=c.substring(e.length+1);return}b.L.push(c)}})}
function M(a,b){if(!b)return a;a.parameters.aff=b.startsWith("-")?b.substring(1):b;return a}function N(a,b){if(!b)return a;b=(b instanceof Array?b:b.split("|")).map(function(c){return c.startsWith("-")?c.substring(1):c});b=new Set([].concat(w(a.H),w(b)));a.H=Array.from(b).filter(function(c){return c});return a}function La(a,b){if(!b)return a;a.parameters.inc=b.startsWith("-")?b.substring(1):b;return a}
L.prototype.toString=function(){var a=[this.Z];this.H.forEach(function(e){a.push("exp-"+e)});for(var b=v(Object.entries(this.parameters)),c=b.next();!c.done;c=b.next()){var d=v(c.value);c=d.next().value;d=d.next().value;a.push(c+"-"+d)}this.L.forEach(function(e){a.push(e)});return a.join("~")};function Ma(){return oa.apply(0,arguments).filter(function(a){return a})}var Va=Ma();Ma("");Ma("");function Wa(a){var b;return(b=document.querySelector('meta[name="'+a+'"]'))==null?void 0:b.getAttribute("content")};var Xa=document.documentElement.getAttribute("site-id")||"(not found)",Ya=new RegExp(/![o0]\d/i);function Za(){var a=new URLSearchParams(decodeURIComponent(document.location.search.toLowerCase())),b=a.get("subid")||"",c=a.get("gmbsrc")||"";a=a.get("mcsubid")||"";var d=b.match(Ya);return[d?b.split(d[0])[0]+d[0]:b,c,a].filter(String)}function $a(){var a=["-ha","-gdn","-adon"];return Za().some(function(b){return a.some(function(c){return b.includes(c)})})}
function ab(){window.dataLayer=window.dataLayer||[];return window.dataLayer}function bb(a){ab().push(Object.assign({},{site_id:Xa},a,{custom_timestamp:Date.now()}))}function O(a){bb({event:"js_error",message:a})};function cb(a){var b=oa.apply(1,arguments);if(b.length===0)return Da(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return Da(c)};var db=new Set("_ga _gl authuser hl gl gclid gad_source gclsrc gmbsrc mcsubid subid suffix".split(" ")),eb=new Set(["suffix"]);function fb(a,b){Array.from(a).forEach(function(c){for(var d=new URL(c.href),e=v(b.entries()),h=e.next();!h.done;h=e.next()){var f=v(h.value);h=f.next().value;f=f.next().value;d.searchParams.set(h,f)}J(c,I(decodeURI(d.toString())))})};var gb=[{I:'a[href^="https://ads.google.com/start/" i]',F:'a[href^="https://ads.google.com/start/"]'},{I:'a[href^="https://business.google.com" i]:not(a[href*="gmbsrc"])',F:'a[href^="https://business.google.com"]',G:"gmbsrc"},{I:'a[href*="./"]'}];
function hb(a){a=a===void 0?"":a;var b=[].concat(w(gb));a&&b.push({I:'a[href*="'+a+'/" i]:not(a[href*="?continue=" i]):not(a[href*="&continue=" i])',F:'a[href*="'+a+'/"]',G:"continue="});a=b.map(function(d){return d.I}).join(",");try{return Array.from(document.querySelectorAll(a))}catch(d){var c=new Set;b.forEach(function(e){try{Array.from(document.querySelectorAll(e.I)).forEach(function(h){c.add(h)})}catch(h){try{e.F&&Array.from(document.querySelectorAll(e.F)).forEach(function(f){var g;e.G&&(!e.G||
(g=f.href)!=null&&g.includes(e.G))||c.add(f)}),e.F&&O("ne_links_alt_success: "+e.F+" when excluding: "+e.G)}catch(f){O("ne_int_links_error: "+f)}}});return Array.from(c)}};var ib=new Map([["/aunz/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/ca-en/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/in/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/uk/think/marketing-strategies/video/create-great-content/",
"https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"],["/us/think/marketing-strategies/video/create-great-content/","https://www.thinkwithgoogle.com/marketing-strategies/video/create-great-content/"]]);
function jb(){for(var a=v(ib.entries()),b=a.next(),c={};!b.done;c={K:void 0},b=a.next()){var d=v(b.value);b=d.next().value;d=d.next().value;c.K=d;document.querySelectorAll('a[href*="'+b+'"]').forEach(function(e){return function(h){try{try{J(h,I(decodeURI(e.K)))}catch(f){}}catch(f){}}}(c))}try{document.querySelectorAll('a[href*="/think"][href*="-gridwall/"]').forEach(function(e){try{e instanceof HTMLAnchorElement&&e.href&&J(e,I(decodeURI(e.href.replace("-gridwall/","/"))))}catch(h){}})}catch(e){}}
;function kb(a,b){return K(a)?N(new L(a),b.split("|")).toString():a.includes(b)?a:a.includes("~")?a.replace("~",b+"~"):a+b}function lb(a,b){return a.includes(b)?a:a+(b.startsWith("-")?"":"-")+b}function mb(){try{document.querySelectorAll('li:has(> a[href*="/essentials/"])').forEach(function(a){a.remove()})}catch(a){}}
function nb(a,b,c){this.country=a;this.lang=b;this.experimentIds=c===void 0?"":c;a.toLowerCase()!=="us"&&mb();try{var d;if(((d=document.querySelector("html"))==null?void 0:d.getAttribute("site-id"))==="twg"){var e;(e=document.querySelector(".glue-breadcrumbs"))==null||e.remove()}}catch(B){O("bgc_subid: error removing breadcrumbs: "+B)}try{jb()}catch(B){O("bgc_subid: error fixing article links: "+B)}try{if((document.documentElement.dataset.dcsLog||"").startsWith("404"))for(var h=v(document.querySelectorAll('a[href^="./"], a[href*="/us/us/"], a[href*="/uk/uk/"], a[href*="/in/in/"], a[href*="/aunz/aunz/"], a[href*="/ca-en/ca-en/"]')),
f=h.next();!f.done;f=h.next()){var g=f.value,k=g.getAttribute("href");if(k){k=k.replaceAll(/\.\.\//gi,"").replace("./","https://business.google.com/");k=k.replace("/us/us/","/us/").replace("/uk/uk/","/uk/").replace("/in/in/","/in/").replace("/aunz/aunz/","/aunz/").replace("/ca-en/ca-en/","/ca-en/");try{J(g,I(decodeURI(k)))}catch(B){}}}}catch(B){O("bgc_subid: error fixing 404 page links: "+B)}b=(new URL(document.location.href)).searchParams;a=new URLSearchParams;c=v(b.keys());for(d=c.next();!d.done;d=
c.next())d=d.value,e=d.toLowerCase(),(db.has(e)||e.startsWith("utm"))&&a.set(e,b.get(d));try{fb(hb(document.location.hostname),a)}catch(B){O("bgc_subid: error updating internal links: "+B)}b=v(eb.values());for(c=b.next();!c.done;c=b.next())a.delete(c.value);try{var l=decodeURI(a.get("subid")||""),m=decodeURI(a.get("gmbsrc")||"");l&&a.set("subid",kb(l,this.experimentIds));m&&a.set("gmbsrc",lb(m,this.experimentIds));for(var q=new URLSearchParams(a),n=v(document.querySelectorAll("a[href*=ads\\.google\\.com i]")),
r=n.next();!r.done;r=n.next()){var x=r.value,A=new URL(x.href);l=void 0;x.href.includes("ads.google.com/signup")&&((l=x.textContent)==null?void 0:l.trim())==="Get started"&&(x.textContent="Start now");x.removeAttribute("target");for(var Na=v(q.entries()),sa=Na.next();!sa.done;sa=Na.next()){var Oa=v(sa.value),Kb=Oa.next().value,Lb=Oa.next().value;A.searchParams.set(Kb,Lb)}var Pa=decodeURI(A.searchParams.get("subid")||"");this.experimentIds&&Pa&&A.searchParams.set("subid",kb(Pa,this.experimentIds));
J(x,I(decodeURI(A.toString())))}fb(document.querySelectorAll("a[href*=analytics\\.google\\.com i]"),a);for(var Mb=new URLSearchParams(a),Qa=v(document.querySelectorAll("a[href*=gmbsrc i]")),ta=Qa.next();!ta.done;ta=Qa.next()){for(var Ra=ta.value,U=new URL(Ra.href),Sa=v(Mb.entries()),ua=Sa.next();!ua.done;ua=Sa.next()){var Ta=v(ua.value),Nb=Ta.next().value,Ob=Ta.next().value;U.searchParams.set(Nb,Ob)}var Ua=decodeURI(U.searchParams.get("gmbsrc")||"");this.experimentIds&&Ua&&U.searchParams.set("gmbsrc",
lb(Ua,this.experimentIds));J(Ra,I(decodeURI(U.toString())))}var D=new URLSearchParams(a);D.has("mcsubid")||D.set("mcsubid",this.country+"-"+this.lang+"-bgc-mc-web!o3");D.has("hl")||this.lang==="unknown"||D.set("hl",this.lang);D.set("fmp",this.country.toLowerCase()==="us"?"2":"1");D.set("referral","true");this.experimentIds&&D.set("variant",this.experimentIds);fb(document.querySelectorAll("a[href*=mcsubid i], a[href*=merchants\\.google\\.com i]"),D)}catch(B){O("bgc_subid: error updating ctas: "+B)}}
;function P(){var a=window.location.href;a=a===void 0?window.location.href:a;var b=window.___jsl=window.___jsl||{};b.cfg=b.cfg||{};b=b.cfg;for(var c=["googleapis.config","sessionIndex"],d=0,e=c.length;b&&typeof b==="object"&&d<e;++d)b=b[c[d]];b=d===c.length&&b!==void 0?b:void 0;"string"===typeof b&&b.length>254&&(b=null);b==null&&(b=window.__X_GOOG_AUTHUSER);"string"===typeof b&&b.length>254&&(b=null);b==null&&(c=window.google)&&(b=c.authuser);"string"===typeof b&&b.length>254&&(b=null);if(b==null){a=
a||window.location.href;b=RegExp("([#].*&|[#])authuser=([^&#]*)","g");c=RegExp("([?#].*&|[?#])authuser=([^&#]*)","g");if(b=a&&(b.exec(a)||c.exec(a)))try{var h=decodeURIComponent(b[2])}catch(f){}b=h||null;b==null&&(b=(h=a.match(Ja))?h[1]:null)}b==null?h=null:(b=String(b),b.length>254&&(b=null),h=b);if(h)return isNaN(Number(h))?0:Number(h);h=(h=document.cookie.match(RegExp("(^| )ADS_CUSTOMER_ACCOUNT_SESSION_INFO=([^;]+)")))?h[2]:null;return(h=h==null?void 0:h.match(RegExp("authuser-([0-9]+)")))&&Number(h[1])||
0};function ob(){var a,b=((a=window.navigator)==null?void 0:a.userAgent.toLowerCase())||"";if(RegExp("(ipad|tablet|(android(?!.*mobile))|(windows(?!.*phone)(.*touch))|kindle|playbook|silk|(puffin(?!.*(IP|AP|WP))))").test(b))return"TABLET";var c,d,e;return/Macintosh/i.test((c=navigator)==null?void 0:c.userAgent)&&((d=navigator)==null?0:d.maxTouchPoints)&&((e=navigator)==null?void 0:e.maxTouchPoints)>1?"IPAD":/android|windows phone|Mobile/i.test(b)||/iPhone|iPod/.test(b)&&!window.MSStream?"MOBILE":"DESKTOP"}
var Q=/\{POSITION}|\{position}|\{Position}/,pb=new RegExp(/({locale}-{lang})/),qb=new RegExp(/![o0]\d/i),R=RegExp(/((!o2)-[A-Za-z]{1,}-[A-Za-z]{2}-[A-Za-z0-9]{2}-[0-9]{2})/),S=RegExp(/((!o3)[_-][A-Za-z]+(?:-[A-Za-z0-9]+)*)/);function rb(a){var b=a.indexOf("~");return b>-1?a.substring(b+1):""}
function sb(a,b){var c=T.g;if(K(a))return N(La(M(new L(a),V()),b),c).toString();var d=decodeURI(a),e=d.split(qb)[0];a=rb(d);var h;d=(((h=d.match(qb))==null?void 0:h[0])||"")+"-";b=e+d+b;h=V();b.toLowerCase().includes(h.toLowerCase())||(b+="-"+h);b.toLowerCase().includes(c.toLowerCase())||(b+=c);return b+(a?"~"+a:"")}
function V(){var a=window.location.pathname.toLowerCase();return a.endsWith("/google-ads/")||a.endsWith("/welcome-offer/")?(new URLSearchParams(window.location.search)).get("affiliateId")||document.documentElement.dataset.lastSeenAffiliateId||"":""}
function T(a,b,c,d){var e=this;d=d===void 0?"":d;this.u=[];this.locale=a||"root";this.country=b;this.language=c;this.experimentIds=d;this.A=document.querySelectorAll('a[href*=subid], a[href*="https://play.google.com/"], a[href*="https://apps.apple.com/"]');this.v=P();a=(new URLSearchParams(window.location.search)).get("subid");var h=(new URLSearchParams(window.location.search)).get("suffix");a&&h&&(h=null);this.g=Ia(a||"").toString();this.C=Ia(h||"").toString();var f=document.querySelector("html");
this.l=f.getAttribute("ci-appendix")||"";this.o=f.getAttribute("suf-subid")||"";switch(ob()){case "DESKTOP":this.h="c";break;case "MOBILE":this.h="m";break;case "TABLET":this.h="t";break;case "IPAD":this.h="t";break;default:this.h="a"}h&&(this.l=h,this.o=sb(this.o,this.l));new nb(b,c,d);b=v(this.A);for(c=b.next();!c.done;c=b.next())c=c.value,c.classList.add("so-rpl"),this.g&&!tb(c)&&(ub(this,c),this.g.match(Q)&&vb(c)),W(c,this.h,this.v),wb(c,this.locale);this.g&&xb(this);this.g||a||!h||(yb(this),
zb(this));document.addEventListener("CTA:updatesuffix",function(g){var k=g.detail;g=k.resetInternalLinks;var l=k.suffix,m=k.suffixHasExperiment;k=k.experimentArmSubid;zb(e,g?"":l);for(var q=v(document.querySelectorAll('a[href*=subid], a[href*="https://play.google.com/"], a[href*="https://apps.apple.com/"]')),n=q.next();!n.done;n=q.next())if(n=n.value,l)Ab(n,l,m,k);else if(e.g)ub(e,n,g),W(n,e.h,e.v);else{var r=document.querySelector("html");if(K(e.o)){var x;r.hasAttribute("no-codeless-incentive")?
x="":x=(new L(e.o)).parameters.inc||"";Ab(n,x);break}var A=e.o.includes("!o2")?"!o2":"!o3";Ab(n,r.hasAttribute("no-codeless-incentive")?"":e.o.split(A)[1])}})}
function Ab(a,b,c,d){c=c===void 0?!1:c;d=d===void 0?"":d;var e=V(),h=T.g,f=new URL(a.href),g=decodeURI(f.searchParams.get("subid")||"");g&&(f.searchParams.set("authuser",String(P())),K(g)?(c&&d&&(b=b.replace(d,"")),b=N(M(La(new L(g),b),e),h),f.searchParams.set("subid",b.toString())):(c=rb(g),d=g.search(qb)||-1,d=d!==-1?d+3:g.length,g=g.substring(0,d)+((b&&b.charAt(0)!=="-"?"-":"")+b),g.toLowerCase().includes(e.toLowerCase())||(g+="-"+e),g.toLowerCase().includes(h.toLowerCase())||(g+=h),f.searchParams.set("subid",
g+(c?"~"+c:""))),J(a,I(decodeURI(f.href))))}function xb(a){var b=P();a.u=hb(window.location.hostname);for(var c=v(a.u),d=c.next();!d.done;d=c.next())if(d=d.value,d.classList.add("so-rpl"),!tb(d,!1)){var e=d.href;J(d,I(e+(e.indexOf("?")>0?"&":"?")+"subid="+a.g));W(d,a.h,b);a.g.match(Q)&&vb(d)}}function yb(a){for(var b=P(),c=v(a.A),d=c.next();!d.done;d=c.next()){d=d.value;var e=sb(d.href,a.l);J(d,I(e));W(d,a.h,b);decodeURI(d.href).match(Q)&&vb(d);wb(d,a.locale)}}
function zb(a,b){b=b===void 0?"":b;a.u=hb(window.location.hostname);for(var c=v(a.u),d=c.next();!d.done;d=c.next()){d=d.value;var e=new URL(d.href);b?e.searchParams.has("subid")?Ab(d,b):(e.searchParams.set("suffix",b),J(d,I(decodeURI(e.href)))):(a.C?e.searchParams.set("suffix",a.C):(e.searchParams.delete("suffix"),a.g&&e.searchParams.set("subid",a.g)),J(d,I(decodeURI(e.href))))}}
function ub(a,b,c){c=c===void 0?!1:c;if(K(a.g)){var d=c;d=d===void 0?!1:d;var e=new L(a.g);c=new URL(b.href);var h="",f=b.href.split(R)[1]||"";d=a.l?a.l:d?"":b.href.split(S)[1]||"";f&&!a.g.includes(f)?h=f:d&&!a.g.includes(d)&&(h=d);N(e,T.g);M(e,V());La(e,h);c.searchParams.set("subid",e.toString());J(b,I(c.toString()))}else{e=T.g;h=(h=V())?"-"+h:"";f=new URL(b.href);d=a.g;var g=b.href.split(R)[1]||"";c=a.l?"!o3"+e+a.l:c?"":b.href.split(S)[1]||"";g&&!a.g.includes(g)?d=a.g.match(R)?a.g.replace(a.g.split(R)[1],
h+e+g):a.g+g.slice(3):c&&!a.g.includes(c)&&(d=a.g.match(S)?a.g.replace(a.g.split(S)[1],c):a.g+e+c.slice(3));f.searchParams.set("subid",d);J(b,I(f.toString()))}}
function W(a,b,c){var d=decodeURI(a.href),e=new URL(d);d.includes("subid")&&d.includes("{device}")&&(e=new URL(d.replace("{device}",b)));b=(new URL(window.location.href)).searchParams;d=new URLSearchParams;for(var h=v(b.keys()),f=h.next();!f.done;f=h.next())f=f.value,(Bb.has(f)||f.startsWith("utm_"))&&d.set(f,b.get(f));b=v(d.entries());for(d=b.next();!d.done;d=b.next())h=v(d.value),d=h.next().value,h=h.next().value,e.searchParams.set(d,h);e.searchParams.set("authuser",String(c));f=e.searchParams.get("subid");
var g=V();c=g?"-"+g:"";b=f&&!f.toLowerCase().includes(g.toLowerCase());d=T.g;h=f&&!f.toLowerCase().includes(d.startsWith("-")?d.substring(1):d);f&&(h||b)&&(K(f)?e.searchParams.set("subid",N(M(new L(f),g),d).toString()):(f=f.split(/~(.*)/),e.searchParams.set("subid",f[0]+(b?c:"")+(h?d:"")+(f[1]?"~"+f[1]:""))));J(a,I(decodeURI(e.toString())))}function wb(a,b){if(b!=="root"){var c=decodeURI(a.href);c.match(pb)&&(c=c.replace(pb,b.split("_").reverse().join("-")),J(a,I(decodeURI(c))))}}
function vb(a){var b=a==null?void 0:a.getAttribute("data-position");b&&J(a,I(a.href.replace(Q,b)))}function tb(a,b){var c;return!!(a==null?0:(c=a.getAttribute(b===void 0||b?"data-url":"href"))==null?0:c.includes("subid"))}t.Object.defineProperties(T,{g:{configurable:!0,enumerable:!0,get:function(){return document.documentElement.getAttribute("mte")||""}}});var Bb=new Set("_ga _gl gclid gad_source gclsrc gmbsrc mcsubid".split(" "));var Cb={AED:{i:"\u062f.\u0625.",j:"\u062f.\u0625.",code:"AED",divisor:1,D:"\u062f\u0631\u0647\u0645"},ARS:{i:"AR$",j:"$",code:"ARS"},AUD:{i:"AU$",j:"$",code:"AUD"},BGN:{i:"\u043b\u0432.",j:"\u043b\u0432",code:"BGN"},BRL:{i:"R$",j:"R$",code:"BRL"},CAD:{i:"CA$",j:"$",code:"CAD"},CHF:{i:"Fr.",j:"\u20a3",code:"CHF"},CNY:{i:"CN\u00a5",j:"\u5143",code:"CNY"},CZK:{i:"K\u010d",j:"K\u010d",code:"CZK"},DKK:{i:"kr.",j:"kr",code:"DKK"},EGP:{i:"E\u00a3",j:"\u062c.\u0645.",code:"EGP"},EUR:{i:"\u20ac",j:"\u20ac",
code:"EUR"},GBP:{i:"\u00a3",j:"\u00a3",code:"GBP"},HKD:{i:"HK$",j:"$",code:"HDK"},HUF:{i:"Ft",j:"Ft",code:"HUF"},IDR:{i:"Rp",j:"\u20b9",code:"IDR"},ILS:{i:"\u20aa",j:"\u20aa",code:"ILS"},INR:{i:"Rs.",j:"\u20b9",code:"INR"},JPY:{i:"\u00a5",j:"\u00a5",code:"JPY",divisor:1E4,D:"\u4e07\u5186"},KRW:{i:"\u20a9",j:"\u20a9",code:"KRW",divisor:1E4,D:"\ub9cc\uc6d0"},MXN:{i:"MX$",j:"$",code:"MXN"},NZD:{i:'NZ$"',j:"$",code:"NZD"},NOK:{i:'kr"',j:"kr",code:"NOK"},PHP:{i:"\u20b1",j:"\u20b1",code:"Php"},PLN:{i:"z\u0142",
j:"z\u0142",code:"PLN"},RON:{i:"L",j:"L",code:"RON"},SAR:{i:"SR",j:"\u0631.\u0633.",code:"SAR"},SEK:{i:"kr",j:"kr",code:"SEK"},SGD:{i:"S$",j:"$",code:"SGD"},THB:{i:"\u0e3f",j:"\u0e3f",code:"THB",divisor:1,D:"\u0e1a\u0e32\u0e17"},TRY:{i:"TL",j:"\u20ba",code:"TRY"},TWD:{i:"NT$",j:"\u5713",code:"TWD"},UAH:{i:"\u20b4",j:"\u0433\u0440\u043d",code:"UAH"},AR_USD:{i:"\u062f\u0648\u0644\u0627\u0631 \u0623\u0645\u0631\u064a\u0643\u064a",j:"\u062f\u0648\u0644\u0627\u0631 \u0623\u0645\u0631\u064a\u0643\u064a",
code:"USD"},USD:{i:"$",j:"$",code:"USD"},ZAR:{i:"R",j:"R",code:"ZAR"}},Db={ar_ae:{currencyCode:"AED",format:"{units} {divisorSymbol}",m:","},ar_all:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_dz:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_jo:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_kw:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_ma:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_qa:{currencyCode:"AR_USD",
format:"{units} {symbolNative}",m:","},ar_tn:{currencyCode:"AR_USD",format:"{units} {symbolNative}",m:","},ar_eg:{currencyCode:"EGP",format:"{units} {symbolNative}"},ar_sa:{currencyCode:"SAR",format:"{units} {symbolNative}"},bg_bg:{currencyCode:"BGN",format:"{units} {symbolNative}"},ca_es:{currencyCode:"EUR",format:"{units} {symbolNative}"},cs_cz:{currencyCode:"CZK",format:"{units} {symbolNative}",m:" "},da_dk:{currencyCode:"DKK",format:"{units} {symbolNative}",m:"."},de_at:{currencyCode:"EUR",format:"{units} {symbolNative}"},
de_ch:{currencyCode:"CHF",format:"{code} {units}"},de_de:{currencyCode:"EUR",format:"{units} {symbolNative}"},el_gr:{currencyCode:"EUR",format:"{units} {symbolNative}"},en_ae:{currencyCode:"AED",format:"{units} {code}"},en_au:{currencyCode:"AUD",format:"{symbolNative}{units}"},en_ca:{currencyCode:"CAD",format:"{symbolNative}{units} {code}"},en_cy:{currencyCode:"EUR",format:"{units} {symbolNative}"},en_eg:{currencyCode:"EGP",format:"{code} {units}",m:","},en_hk:{currencyCode:"HKD",format:"{symbol}{units}"},
en_id:{currencyCode:"IDR",divisor:1E6,D:"jt",format:"{symbol} {units}{divisorSymbol}",m:"."},en_ie:{currencyCode:"EUR",format:"{symbolNative}{units}"},en_in:{currencyCode:"INR",format:"{symbolNative}{units}",m:","},en_ng:{currencyCode:"USD",format:"{symbolNative}{units}"},en_nz:{currencyCode:"NZD",format:"{symbolNative}{units}"},en_ph:{currencyCode:"PHP",format:"{code} {units}",m:","},en_pk:{currencyCode:"USD",format:"{symbolNative}{units} {code}"},en_sa:{currencyCode:"SAR",format:"{code} {units}"},
en_sg:{currencyCode:"SGD",format:"{symbolNative}{units}"},en_uk:{currencyCode:"GBP",format:"{symbolNative}{units}"},en_us:{currencyCode:"USD",format:"{symbolNative}{units}"},en_za:{currencyCode:"ZAR",format:"{symbolNative}{units}"},"es-419_ar":{currencyCode:"ARS",format:"{units} {code}",m:"."},es_es:{currencyCode:"EUR",format:"{units} {symbolNative}"},es_us:{currencyCode:"USD",format:"{symbolNative}{units}"},"es-419_cl":{currencyCode:"USD",format:"{code} {symbolNative}{units}"},"es-419_co":{currencyCode:"USD",
format:"{code} {symbolNative}{units}"},"es-419_mx":{currencyCode:"MXN",format:"{code} {units}",m:","},"es-419_pe":{currencyCode:"USD",format:"{code} {symbolNative}{units}"},et_ee:{currencyCode:"EUR",format:"{units} {symbolNative}"},fi_fi:{currencyCode:"EUR",format:"{units} {symbolNative}",m:" "},fr_all:{currencyCode:"USD",format:"{code} {symbolNative}{units}"},fr_be:{currencyCode:"EUR",format:"{units} {symbolNative}"},fr_ca:{currencyCode:"CAD",format:"{units} {symbolNative} {code}"},fr_ch:{currencyCode:"CHF",
format:"{code} {units}"},fr_fr:{currencyCode:"EUR",format:"{units} {symbolNative}"},he_il:{currencyCode:"ILS",format:"{symbolNative}{units}"},hr_hr:{currencyCode:"EUR",format:"{units} {symbolNative}"},hu_hu:{currencyCode:"HUF",format:"{units} {symbolNative}",m:" "},id_id:{currencyCode:"IDR",divisor:1E6,D:"jt",format:"{symbol} {units}{divisorSymbol}",m:"."},it_it:{currencyCode:"EUR",format:"{units} {symbolNative}"},iw_il:{currencyCode:"ILS",format:"{symbolNative}{units}"},ja_jp:{currencyCode:"JPY",
format:"{units} {divisorSymbol}",m:","},ko_kr:{currencyCode:"KRW",format:"{units}{divisorSymbol}"},lt_lt:{currencyCode:"EUR",format:"{units} {symbolNative}"},lv_lv:{currencyCode:"EUR",format:"{units} {symbolNative}"},nl_be:{currencyCode:"EUR",format:"{symbolNative} {units}"},nl_nl:{currencyCode:"EUR",format:"{symbolNative}{units}"},no_no:{currencyCode:"NOK",format:"{units} {symbolNative}"},pl_pl:{currencyCode:"PLN",format:"{units} {code}"},"pt-br_br":{currencyCode:"BRL",format:"{symbolNative}{units}",
m:"."},"pt-pt_pt":{currencyCode:"EUR",format:"{units} {symbolNative}"},ro_ro:{currencyCode:"RON",format:"{units} {code}"},ru_by:{currencyCode:"USD",format:"{symbolNative}{units}"},ru_kz:{currencyCode:"USD",format:"{symbolNative}{units}"},sk_sk:{currencyCode:"EUR",format:"{units} {symbolNative}"},sl_si:{currencyCode:"EUR",format:"{units} {symbolNative}"},sr_rs:{currencyCode:"EUR",format:"{units} {symbolNative}"},sv_se:{currencyCode:"SEK",format:"{units} {symbolNative}"},th_th:{currencyCode:"THB",format:"{units} {divisorSymbol}",
m:","},tr_tr:{currencyCode:"TRY",format:"{units} {symbol}",m:"."},uk_ua:{currencyCode:"UAH",format:"{units} {symbolNative}",m:","},"zh-cn_cn":{currencyCode:"CNY",format:"{units}{symbolNative}"},"zh-tw_tw":{currencyCode:"TWD",format:"{symbol} {units}"}};
function Eb(a,b,c){var d=Db[b],e=a.startsWith("ar")&&d.currencyCode==="AR_USD"&&c.currencyCode==="USD",h=Cb[e?"AR_USD":c.currencyCode]||null;if(!d||!h)return"{code} {units}".replace("{units}",c.units.toString()).replace("{code}",c.currencyCode);b=d.m;var f=h.code,g=h.i,k=h.j;e=c.currencyCode===d.currencyCode||e;var l=d.divisor||h.divisor||1;h=d.D||h.D||"";c=e?c.units/l:c.units;d=e?d.format:"{code} {units}";e=c.toString();b&&(e=c.toString().replace(/\B(?=(\d{3})+(?!\d))/g,b));if(a==="en_id"||a==="id_id")e=
c.toLocaleString(a.replace("_","-"));return d.replace("{symbolNative}",k).replace("{symbol}",g).replace("{units}",e).replace("{code}",f).replace("{divisorSymbol}",h)}function Fb(a,b,c){return Eb(a,a.toLowerCase(),{currencyCode:b,units:c,nanos:0})}for(var Gb=["formatCurrencyWithAmount"],X=va,Y;Gb.length&&(Y=Gb.shift());)Gb.length||Fb===void 0?X[Y]&&X[Y]!==Object.prototype[Y]?X=X[Y]:X=X[Y]={}:X[Y]=Fb;var Hb={"ar-all":{ae:"ar_ae",dz:"ar_dz",eg:"ar_eg",jo:"ar_jo",kw:"ar_kw",ma:"ar_ma",qa:"ar_qa",sa:"ar_sa",tn:"ar_tn"},aunz:{au:"en_au",nz:"en_nz"},br:{br:"pt-br_br",pt:"pt-pt_pt"},de:{de:"de_de",at:"de_at",ch:"de_ch"},"en-all":{us:"en_us",ae:"en_ae",bg:"bg_bg",by:"ru_by",cy:"en_cy",dk:"da_dk",ee:"et_ee",eg:"en_eg",fi:"fi_fi",gr:"el_gr",hk:"en_hk",hr:"hr_hr",hu:"hu_hu",id:"en_id",ie:"en_ie",kz:"ru_kz",lt:"lt_lt",lv:"lv_lv",ng:"en_ng",no:"no_no",ph:"en_ph",pk:"en_pk",rs:"sr_rs",sa:"en_sa",sg:"en_sg",
si:"sl_si",sk:"sk_sk",ua:"uk_ua",za:"en_za"},"es-all":{ar:"es-419_ar",cl:"es-419_cl",co:"es-419_co",mx:"es-419_mx",pe:"es-419_pe",us:"es_us"},fr:{fr:"fr_fr",be:"fr_be",ch:"fr_ch",dz:"fr_all",ma:"fr_all",tn:"fr_all"},nl:{nl:"nl_nl",be:"nl_be"},uk:{ie:"en_ie",uk:"en_uk"}};function Ib(a){a=a===void 0?window:a;return(new URLSearchParams(a.location.search)).get("affiliateId")||""}
function Jb(a){var b,c,d,e,h,f;return F(function(g){switch(g.g){case 1:if(!window.location.pathname.toLowerCase().endsWith("/google-ads/referrals/"))return g.return();b=null;g.h=2;if(!a){c=null;g.g=4;break}return z(g,a.readReferrerSignals(),5);case 5:c=g.u;case 4:b=c;g.g=3;g.h=0;break;case 2:C(g);case 3:if(!b||!b.creditsEarned)return g.return();d=b.creditsEarned;e=document.querySelector(".ion-snowflake-module.ion-referrals__tracker");if(f=(h=e)==null?void 0:h.querySelector(".ion-referrals__tracker-progress-details-title")){var k=
document.documentElement.getAttribute("locale")||"";a:{var l,m=(l=document.documentElement.dataset.forcedCurrencyLocale)!=null?l:"";if(m)var q=m;else{m=document.documentElement.getAttribute("is-bgc")==="true";var n;l=(n=document.documentElement.dataset.dcsEffectiveCountryCode)!=null?n:"";n=k.toLowerCase();if(m&&l&&(m=(q=document.documentElement.getAttribute("bgc-locale"))!=null?q:"",q=Hb[m])){q=q[l];break a}q=n}}k=Eb(k,q,d);f.textContent=k}return g.return()}})}
function Pb(a){var b=b===void 0?window:b;var c,d,e,h,f,g,k,l,m,q;F(function(n){switch(n.g){case 1:if(b.location.pathname.toLowerCase().endsWith("/google-ads/welcome-offer/"))return(c=Ib(b))&&b.localStorage.setItem("GAR_AFFILIATE_ID",c),n.return();n.h=2;return z(n,Jb(a),4);case 4:n.g=3;n.h=0;break;case 2:C(n);case 3:if(!b.location.pathname.toLowerCase().endsWith("/google-ads/"))return n.return();d=null;n.h=5;if(!a){e=null;n.g=7;break}return z(n,a.getAdsAccounts(),8);case 8:e=n.u;case 7:d=e;n.g=6;n.h=
0;break;case 5:C(n);case 6:f=(((h=d)==null?void 0:h.customersList.length)||0)>0;g=document.documentElement.dataset.isLoggedIn==="true";k=document.documentElement.dataset.lastSeenAffiliateId||window.localStorage.getItem("GAR_AFFILIATE_ID")||"";try{document.querySelectorAll(".referral-reminder-banner").forEach(function(r){r.dataset.referralExp==="signed-in"?g||r.remove():r.dataset.referralExp==="signed-out"&&g&&r.remove()}),l=!!k&&!f,m=!l&&f&&document.documentElement.dataset.garIsEligible==="true",
document.querySelectorAll(".referral-reminder-banner--unlock-referral").forEach(function(r){l?(O("[referrals] Showing referee offer banner."),r.classList.remove("hidden")):r.remove()}),q=!1,document.querySelectorAll(".referral-reminder-banner--refer-now, .referral-reminder-banner--disclaimer").forEach(function(r){m?(q=!0,r.classList.remove("hidden")):r.remove()}),q&&O("[referrals] Showing referrer banner]")}catch(r){}n.g=0}})};function Qb(){return F(function(a){return a.return(new Promise(function(b,c){var d=setTimeout(function(){clearTimeout(d);c(Error("Timeout"))},15E3)}))})}
function Rb(){var a=this;this.g=null;this.getAdsAccounts=function(){var c,d;return F(function(e){switch(e.g){case 1:return e.h=2,z(e,a.h,4);case 4:return a.g?z(e,(c=a.g)==null?void 0:c.getAdsAccounts(),5):e.return({customersList:[],hasAccount:!1});case 5:return d=e.u,e.return(d);case 2:return C(e),e.return({customersList:[],hasAccount:!1})}})};this.readReferrerSignals=function(){var c;return F(function(d){switch(d.g){case 1:return d.h=2,z(d,a.h,4);case 4:return a.g?z(d,(c=a.g)==null?void 0:c.readReferrerSignals(),
5):d.return({});case 5:return d.return(d.u);case 2:return C(d),d.return({})}})};var b=Array.from(document.querySelectorAll("script")).find(function(c){var d;return c==null?void 0:(d=c.src)==null?void 0:d.includes("marketing_analytics_client_grpc.min.js")});this.h=new Promise(function(c,d){return F(function(e){if(e.g==1){if(a.g=window.MarketingClient)return O("MarketingClient already available"),c(),e.return();if(!b)return O("MarketingClient script not found"),d(Error("MarketingClient script not found")),
e.return();e.h=2;return z(e,Promise.race([new Promise(function(h){b.addEventListener("load",function(){a.g=window.MarketingClient;a.g?h():(O("MarketingClient not attached to window"),d(Error("MarketingClient not attached to window")))})}),Qb()]),4)}if(e.g!=2)return c(),e.return();C(e);O("Could not await MarketingClient");d(Error("Could not await MarketingClient"));return e.return()})})}
Rb.prototype.recordInPageInteraction=function(a,b,c){var d=this,e;return F(function(h){return h.g==1?z(h,d.h,2):z(h,(e=d.g)==null?void 0:e.recordInPageInteraction(a,b,c),0)})};var Sb=ca(["https://ads.google.com/aw/google_ads_prefetch.js?paths=/aw,/aw_essentials,/aw_express/management"]);
function Tb(a){a.toLowerCase()!=="cn"&&window.setTimeout(function(){var b=document.createElement("script");b.async=!0;var c=cb(Sb);if(c instanceof Ca)c=c.g;else throw Error("");b.src=c;var d;c=b.ownerDocument;c=c===void 0?document:c;var e;c=(e=(d=c).querySelector)==null?void 0:e.call(d,"script[nonce]");(d=c==null?"":c.nonce||c.getAttribute("nonce")||"")&&b.setAttribute("nonce",d);d=document.querySelector("script");if(d==null?0:d.parentNode)d.parentNode.insertBefore(b,d);else{var h;(h=document.querySelector("head"))==
null||h.appendChild(b)}},3E3)};var Ub,Vb=document.documentElement.getAttribute("mte")||"",Z=[].concat(w(new Set([].concat(w(Va),w(Vb.split("|"))).filter(String)))).join("|");$a()&&(Z=Z.replace("-ahpm-0000000174-0000000000","").replace("-ahpm-0000000174-0000000001",""));Z&&document.documentElement.setAttribute("mte",Z);Ub=Z;var Wb=$a();document.documentElement.getAttribute("subid-param-name")||document.documentElement.setAttribute("subid-param-name","subid");
var Xb=(Wa("isEom")||"true")==="true",Yb=(Wa("dma-sharing-enabled-for-all-cps")||"false")==="true",Zb={V:Xb,U:Yb},$b=Zb.U,ac=Zb.V||!$b;(function(){ab().push(arguments)})("consent","default",{ad_storage:ac?"denied":"granted",ad_user_data:ac?"denied":"granted",ad_personalization:ac?"denied":"granted",analytics_storage:"granted",ads_data_redaction:ac?!0:!1,url_passthrough:!0});
var bc,cc=String((Wa("isEea")||"true")==="true"),dc=window.document.documentElement.dataset.garIsEligible==="true",ec=window.document.documentElement.dataset.garHasCreatedAffiliateId==="true",fc=window.location.pathname.toLowerCase().endsWith("/referrals/")?dc?ec?"eligible":"eligibility_pending":ec?"eligibility_paused":"ineligible":null;
bc=Object.assign({},{event:"on_pageload",locale:(document.documentElement.hasAttribute("data-root")?"root_":"")+(document.documentElement.getAttribute("locale")||"unknown"),site_id:"agc",login_status:String(document.documentElement.getAttribute("data-is-logged-in")==="true"),experiments:Ub||void 0,is_bgc:"true",is_eea:cc,last_modified_date:document.documentElement.getAttribute("last-modified-date")||document.documentElement.getAttribute("publish-date")||""},fc&&{referrers_eligibility:fc},{u_agent:window.navigator.userAgent});
bb(bc);document.querySelector('meta[name="isEom"]')||O("["+document.documentElement.getAttribute("locale")+(document.documentElement.getAttribute("data-root")?"+root":"")+"] !EOM "+window.location.origin+window.location.pathname);!window.location.pathname.includes("/start/")&&Wb&&O("org_subs: "+Za().join(","));
function hc(){document.querySelectorAll(".ion-page-banner--cyo").forEach(function(a,b){if(b>0)try{a.remove()}catch(c){O("Couldn't remove cyo-banner-"+b+": "+c.message)}});document.querySelectorAll(".ion-cyoi-offers").forEach(function(a,b){if(b>0)try{a.remove()}catch(c){O("Couldn't remove cyo-offer-"+b+": "+c.message)}})}
function ic(){var a=document.documentElement.dataset.highSubidSuffix||"";a.includes("lto")||decodeURIComponent(a).includes("|")||document.querySelectorAll('[data-is-lto="true"]').forEach(function(b){try{b.remove()}catch(c){O("Couldn't remove LTO module: "+c.message)}})}function jc(a){a.childNodes.length?a.childNodes.forEach(function(b){jc(b)}):a.textContent=(a.textContent||"").replaceAll("\u200b","").replaceAll(/\n\s+/g," ")}new URL(window.location.href);
function kc(){try{window.location.hostname.endsWith("corp.goog")||(hc(),ic()),document.querySelectorAll(".with-space-around, span[data-disable-budou]").forEach(function(d){jc(d)})}catch(d){}var a=document.documentElement.getAttribute("locale")||"root",b=a.split("_")[0]||"unknown",c=a.split("_")[1]||"unknown";try{Tb(c)}catch(d){}try{new T(a,c,b,Ub)}catch(d){O("["+a+"]: "+d.message)}a=null;try{a=new Rb}catch(d){}try{Pb(a)}catch(d){}try{(window.location.pathname.toLowerCase().endsWith("/accelerate/gml-announcements/")||
window.location.pathname.toLowerCase().endsWith("/accelerate/announcements/"))&&Array.from(document.querySelectorAll('a[href*="/products/ads-commerce/new-AI-tools-brands-youtube-creators/"]')).forEach(function(d){J(d,I("https://blog.google/products/ads-commerce/new-tools-brands-youtube-creators/"));var e=document.createElement("span");e.textContent=" ";d.insertAdjacentElement("afterend",e);d.textContent&&(d.textContent=d.textContent.trim())})}catch(d){}}
document.readyState==="interactive"||document.readyState==="complete"?kc():document.addEventListener("DOMContentLoaded",kc);}).call(this);
