/**
 * Sitemap Generator for Flood Doctor — Main Site Only
 *
 * Generates sitemap-main.xml for the main flood.doctor domain.
 * City subdomain sitemaps are generated by build-cities.ts (using mapCitySlugs
 * for correct nested service paths).
 *
 * Route data imported from config/routes.ts (single source of truth)
 */

import * as fs from 'fs';
import * as path from 'path';
import { ALL_PRERENDER_ROUTES } from '../config/routes';

// Output directory
const OUTPUT_DIR = path.resolve(process.cwd(), 'public/sitemaps');

interface SitemapUrl {
  loc: string;
  priority: string;
  changefreq: string;
}

/**
 * Generate URL entries for main site using ALL_PRERENDER_ROUTES
 */
function getMainUrls(): SitemapUrl[] {
  const baseUrl = 'https://flood.doctor';
  return ALL_PRERENDER_ROUTES.map((route) => ({
    loc: route === '/' ? baseUrl : `${baseUrl}${route.replace(/\/$/, '')}`,
    priority: route === '/' ? '1.0' : '0.8',
    changefreq: 'weekly',
  }));
}

/**
 * Generate XML sitemap content
 */
function generateSitemapXml(urls: SitemapUrl[]): string {
  const today = new Date().toISOString().split('T')[0];

  const urlEntries = urls.map((url) => `  <url>
    <loc>${url.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>
  </url>`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`;
}

/**
 * Ensure output directory exists
 */
function ensureOutputDir(): void {
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }
}

/**
 * Write sitemap to file
 */
function writeSitemap(filename: string, content: string): void {
  const filepath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filepath, content, 'utf-8');
  console.log(`Generated: ${filename}`);
}

/**
 * Main function
 */
function main(): void {
  console.log('Generating main site sitemap for Flood Doctor...\n');

  ensureOutputDir();

  // Generate main site sitemap only
  // City sitemaps are generated by build-cities.ts with correct nested paths
  const mainUrls = getMainUrls();
  const mainSitemap = generateSitemapXml(mainUrls);
  writeSitemap('sitemap-main.xml', mainSitemap);
  console.log(`  - Main site: ${mainUrls.length} URLs`);

  // Sitemap index — main site only
  // Each city subdomain has its own sitemap.xml generated by build-cities.ts
  const today = new Date().toISOString().split('T')[0];
  const sitemapIndex = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://flood.doctor/sitemaps/sitemap-main.xml</loc>
    <lastmod>${today}</lastmod>
  </sitemap>
</sitemapindex>`;
  writeSitemap('sitemap-index.xml', sitemapIndex);

  console.log(`\nDone! Generated 2 sitemap files with ${mainUrls.length} total URLs.`);
}

// Run the generator
main();
